### ISSUE TITLE
Use navigator.hardwareConcurrency for worker pool sizing

### ISSUE THREAD

**Issue by eligrey** [feross/md5-password-cracker.js#2]
I was going to suggest using `navigator.hardwareConcurrency || 8` in https://github.com/feross/md5-password-cracker.js/blob/master/coordinator.js#L1 but your comment indicates that some carry logic will also need to be changed.

Btw, have you ever thought about md5 cracking with WebGL shaders? :P

**Comment by feross** [comment]
Yeah! I've thought about the WebGL shader approach, but after I learned that WebGL lacks integer support, and read an account of someone else who tried to do MD5 cracking using WebGL I gave up. Supposedly, the conversion from float to int for int-based operations is just too slow!

I think we can just leave it at 8. Users with fewer cores will still work fine, just with lots of CPU contention.
